config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  get "tasks" => "tasks#index", as: :all_tasks
  get "tasks/new" => "tasks#new", as: :create_task
  post "tasks" => "tasks#create"
  get "tasks/:id" => "tasks#show", as: :task
  delete "tasks/:id" => "tasks#destroy"

  # Defines the root path route ("/")
  root "tasks#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/task.rb
class Task < ApplicationRecord
  # tite / details / completed (bool)
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

  def index
    @tasks = Task.all;
  end

  def show
    @task = Task.find(params[:id]);
  end

  def new
    @task = Task.new;
  end

  def create
    @task = Task.new(task_params);
    @task.save;
    redirect_to all_tasks_path;
  end

  def destroy
    @task = Task.find(params[:id]);
    @task.destroy;
    redirect_to all_tasks_path, status: :see_other
  end

  private

  def task_params
    params.require(:task).permit(:title, :details);
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/index.html.erb
<h1>All Tasks</h1>
<ul>
  <% @tasks.each do |t| %>
    <li><%= link_to(t.title, task_path(t)) %>
      <%= link_to("🗑", task_path(t),
      data: {turbo_method: :delete, turbo_confirm: "Are you sure?"})
      %>
    </li>
  <% end %>
</ul>
<p><%= link_to("Create Task", create_task_path) %></p>

app/views/tasks/new.html.erb
<%= form_with model: @task do |tf| %>
  <%= tf.label :title %>
  <%= tf.text_field :title %>
  <%= tf.label :details %>
  <%= tf.text_field :details %>
  <%= tf.submit %>
<% end %>
<hr>
<%= link_to("Back", all_tasks_path) %>

app/views/tasks/show.html.erb
<h2><%= @task.title %></h2>
<p><%= @task.details %></p>
<p><%= @task.completed %></p>
<%= link_to("Back", all_tasks_path) %>